Straßenkarte/Models/ViewModels/HomeviewModel.cs
using System;

namespace Straßenkarte.Models.ViewModels
{
    public class HomeViewModel
    {
        public int Id { get; set; }
        public string Tag { get; set; }
        public string Kullanıcı { get; set; }
        public DateTime CreateDate { get; set; }
        public DateTime Comments { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Search { get; set; }
        public string Category { get; set; }
        public string Author { get; set; }
    }
    
}

Straßenkarte/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Straßenkarte.Abstract.Repository;
using Straßenkarte.Abstract.Service;
using Straßenkarte.Enitites;
using Straßenkarte.Models;
using Straßenkarte.Models.ViewModels;
using Straßenkarte.Repository;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Reflection.Metadata;
using System.Threading.Tasks;
using System.Xml;

namespace Straßenkarte.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBlogService blogService;
        private readonly ICategoryService categoryService;

        public HomeController(ILogger<HomeController> logger, IBlogService blogService, ICategoryService categoryService)
        {
            _logger = logger;
            this.blogService = blogService;
            this.categoryService = categoryService;
        }

        [HttpGet]
        public IActionResult Index(int categoryId=0)
        {


            var blog = new BlogsViewModel
            {
                Blogs = blogService.GetByCategoryId(categoryId).ToList(),
                CategoriesSelect = categoryService.GetSelectListItems(),


            };
            return View(blog);

        }
        public IActionResult Contact()
        {
            return View();
        }
        
        public IActionResult PostDetail(int id)
        {

            var blog = blogService.GetById(id);
            var gelen = new BlogViewModel
            {
                BlogTitle = blog.BlogTitle,
                BlogDescription = blog.BlogDescription,
                CreateDate = blog.CreateDate,
                İmageName = blog.ImageUrl,
                CategoryId = blog.CategoryId,
                Id = blog.Id
                

            };
            return View(gelen);
        }
        [HttpGet]
        public IActionResult AllBlog(int page=1, int category=0, string tag=null)
        {
            var result = blogService.GetByCategoryId(category);
            int pageSize = 3;

            if (tag!=null)
            {
                var result2=blogService.SearchTag(tag);
                result = result2;


            }
            if (result.Count>1)
            {
                pageSize = 30;
            }
            var blog = new BlogsViewModel
            {

                Blogs = result.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount = (int)Math.Ceiling(result.Count / (double)pageSize),
                PageSize = pageSize,
                SelectCategory = category,
                CurrentPage = page,



            };

            return View(blog);



        }
        [HttpGet]
        public IActionResult GetBlog(string aranankelime,int page=1)
        {
            int pageSize = 3;
            var result = blogService.Search(aranankelime).ToList();
            var blog = new BlogsViewModel
            {
                Blogs = result.Skip((page - 1) * pageSize).Take(pageSize).ToList(),
                PageCount=(int)Math.Ceiling(result.Count/(double)pageSize),
                PageSize=pageSize,
                CurrentPage=page,


            };

            return View(blog);

        }
    }
}

Straßenkarte/ViewComponents/CategoryListViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Straßenkarte.Abstract.Service;
using Straßenkarte.Models.ViewModels;
using Straßenkarte.Services;
using System;

namespace Straßenkarte.ViewComponents
{
	public class CategoryListViewComponent:ViewComponent
	{
		private readonly ICategoryService categoryService;

		public CategoryListViewComponent(ICategoryService categoryService)
		{
			this.categoryService = categoryService;
		}

		public ViewViewComponentResult Invoke()
		{

			var model = new CategoryModelComponent
			{
				Categories = categoryService.GetAll(),
				SelectValue = Convert.ToInt32(HttpContext.Request.Query["category"])
			};
			return View(model);
		}

	}
}

Straßenkarte/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}


<!-- Page Content -->
<!-- Banner Starts Here -->
<div class="heading-page header-text">
    <section class="page-heading">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-content">
                        <h4>about us</h4>
                        <h2>more about us!</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Banner Ends Here -->


<section class="about-us">
    <div class="container">

        <div class="row">
            <div class="col-lg-12">
                <img src="/images/about-us.jpg" alt="">
                <p>Please tell your friends about TemplateMo website. Thank you. You can browse through different categories of templates such as <a rel="nofollow" href="https://templatemo.com/tag/business" target="_parent">business</a>, <a rel="nofollow" href="https://templatemo.com/tag/portfolio" target="_parent">portfolio</a>, <a rel="nofollow" href="https://templatemo.com/tag/restaurant" target="_parent">restaurant</a>, etc. Pellentesque quis luctus libero. Maecenas pretium molestie erat, ac tincidunt leo gravida ac. Cras ullamcorper eu ipsum eu sollicitudin. Fusce vitae commodo turpis. Integer ullamcorper purus nec justo mollis fermentum. Nunc imperdiet erat nec lacinia laoreet. <br><br>Maecenas faucibus ullamcorper felis vitae finibus. Nullam at quam ut lacus aliquam tempor vel sed ipsum. Donec pellentesque tincidunt imperdiet. Mauris sit amet justo vulputate, cursus massa congue, vestibulum odio. Aenean elit nunc, gravida in erat sit amet, feugiat viverra leo. Phasellus interdum, diam commodo egestas rhoncus, turpis nisi consectetur nibh, in vehicula eros orci vel neque.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-6">
                <h4>Two-One Donec porttitor augue</h4>
                <p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
            </div>
            <div class="col-lg-6">
                <h4>Two-Two Donec porttitor augue</h4>
                <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-4 col-md-6">
                <h4>1-03 Donec porttitor augue</h4>
                <p>Quisque bibendum cursus viverra. Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
            </div>
            <div class="col-lg-4 col-md-6">
                <h4>2-03 Donec porttitor augue</h4>
                <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
            <div class="col-lg-4">
                <h4>3-03 Donec porttitor augue</h4>
                <p>Maecenas et metus nisl. Morbi ac interdum metus. Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-3 col-md-6">
                <h4>01 Four Columns</h4>
                <p>Mauris at ex ipsum. Aenean condimentum urna nisl, eget interdum ante euismod vel. Aliquam at metus sit amet nunc dapibus posuere.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4>02 Four Columns</h4>
                <p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4>03 Four Columns</h4>
                <p>Morbi ac interdum metus. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4>04 Four Columns</h4>
                <p>Aliquam erat volutpat. Donec posuere tortor vel volutpat consequat. Mauris sagittis magna vel tellus semper interdum et id sapien.</p>
            </div>
        </div>

        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                    <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                    <li><a href="#"><i class="fa fa-behance"></i></a></li>
                    <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                </ul>
            </div>
        </div>


    </div>
</section>

Straßenkarte/Views/Home/AllBlog.cshtml
@model BlogsViewModel
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@{
	ViewData["Title"] = "AllBlog";
	Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Banner Starts Here -->
<div class="heading-page header-text">
	<section class="page-heading">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="text-content">
						<h4>Recent Posts</h4>
						<h2>Our Recent Blog Entries</h2>
					</div>
				</div>
			</div>
		</div>
	</section>
</div>

<!-- Banner Ends Here -->
@await Component.InvokeAsync("CategoryList")
<section class="blog-posts grid-system">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="all-blog-posts">
					<div class="row ">
						@foreach (var item in Model.Blogs)
						{
							<div class="col-lg-4">
								<div class="blog-post">
									<div class="blog-thumb">
										<img src="/Img/@item.ImageUrl" alt="" style="height:300px">
									</div>
									<div class="down-content">
										
										<span>Kategori</span>
										<a asp-action="PostDetail" asp-route-id="@item.Id"><h4>@item.BlogTitle</h4></a>
										<ul class="post-info">
											<li><a href="#">Admin</a></li>
											<li><a href="#">@item.CreateDate</a></li>
											<li><a href="#">26 Comments</a></li>
										</ul>
										@if (item.BlogDescription.Length > 200)
										{

											@Html.Raw(item.BlogDescription.Substring(0,199))
											<a asp-action="PostDetail" asp-route-id="@item.Id" target="_parent">Devamı için tıklayınız</a>

										}

										else
										{
											@Html.Raw(item.BlogDescription)
										}
										<div class="post-options">
											<div class="row">
												<div class="col-lg-12">
													<ul class="post-tags">
														<li><i class="fa fa-tags"></i></li>
														<li><a asp-controller="home" asp-action="allblog">@item.Tag</a></li>
													</ul>
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						}


						<product-list-pager 
								current-category="@Model.SelectCategory"
								current-page="@Model.CurrentPage"
								page-count="@Model.PageCount"
								page-size="@Model.PageSize">
						</product-list-pager>

					</div>
				</div>
			</div>

		</div>
	</div>
</section>

Straßenkarte/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}

<!-- Banner Starts Here -->
<div class="heading-page header-text">
    <section class="page-heading">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-content">
                        <h4>contact us</h4>
                        <h2>let’s stay in touch!</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Banner Ends Here -->


<section class="contact-us">
    <div class="container">
        <div class="row">

            <div class="col-lg-12">
                <div class="down-contact">
                    <div class="row">
                        <div class="col-lg-8">
                            <div class="sidebar-item contact-form">
                                <div class="sidebar-heading">
                                    <h2>Send us a message</h2>
                                </div>
                                <div class="content">
                                    <form id="contact" action="" method="post">
                                        <div class="row">
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="name" type="text" id="name" placeholder="Your name" required="">
                                                </fieldset>
                                            </div>
                                            <div class="col-md-6 col-sm-12">
                                                <fieldset>
                                                    <input name="email" type="text" id="email" placeholder="Your email" required="">
                                                </fieldset>
                                            </div>
                                            <div class="col-md-12 col-sm-12">
                                                <fieldset>
                                                    <input name="subject" type="text" id="subject" placeholder="Subject">
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <textarea name="message" rows="6" id="message" placeholder="Your Message" required=""></textarea>
                                                </fieldset>
                                            </div>
                                            <div class="col-lg-12">
                                                <fieldset>
                                                    <button type="submit" id="form-submit" class="main-button">Send Message</button>
                                                </fieldset>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4">
                            <div class="sidebar-item contact-information">
                                <div class="sidebar-heading">
                                    <h2>Contact</h2>
                                </div>
                                <div class="content">
                                    <ul>
                                        
                                        <li>
                                            <h5>Strabenkarte@gmail.com</h5>
                                            <span>EMAIL ADDRESS</span>
                                        </li>
                                        <li>
                                            
                                        </li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-12">
                <div id="map">
                    <iframe src="https://maps.google.com/maps?q=Av.+L%C3%BAcio+Costa,+Rio+de+Janeiro+-+RJ,+Brazil&t=&z=13&ie=UTF8&iwloc=&output=embed" width="100%" height="450px" frameborder="0" style="border:0" allowfullscreen></iframe>
                </div>
            </div>

        </div>
    </div>
</section>

Straßenkarte/Views/Home/GetBlog.cshtml
@model BlogsViewModel
@addTagHelper "*,Microsoft.AspNetCore.Mvc.TagHelpers"
@{
    ViewData["Title"] = "GetBlog";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Banner Starts Here -->
<div class="heading-page header-text">
    <section class="page-heading">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="text-content">
                        <h4>Recent Posts</h4>
                        <h2>Our Recent Blog Entries</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>

<!-- Banner Ends Here -->
<section class="blog-posts grid-system">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="all-blog-posts">
                    <div class="row ">
                        @foreach (var item in Model.Blogs)
                        {
                            <div class="col-lg-4">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="/Img/@item.ImageUrl" alt="" style="height:300px">
                                    </div>
                                    <div class="down-content">
                                        <span>Lifestyle</span>
                                        <a asp-action="PostDetail" asp-route-id="@item.Id"><h4>@item.BlogTitle</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">Admin</a></li>
                                            <li><a href="#">@item.CreateDate</a></li>
                                            <li><a href="#">26 Comments</a></li>
                                        </ul>
                                        @if (item.BlogDescription.Length > 200)
                                        {

                                            @Html.Raw(item.BlogDescription.Substring(0,199))
                                            <a asp-action="PostDetail" asp-route-id="@item.Id" target="_parent">Devamı için tıklayınız</a>

                                        }

                                        else
                                        {
                                            @Html.Raw(item.BlogDescription)
                                        }
                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">Best Templates</a>,</li>
                                                        <li><a href="#">TemplateMo</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        }
                        
                        <blog-list-pager    
                            current-page="@Model.CurrentPage"
                            page-count="@Model.PageCount"
                            page-size="@Model.PageSize">
                        </blog-list-pager>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section>

Straßenkarte/Views/Home/Index.cshtml
@using Straßenkarte.Enitites;
@model BlogsViewModel

@{
    ViewData["Title"] = "Home Page";
    
}


<div class="main-banner header-text">
    <div class="container-fluid">
        <div class="owl-banner owl-carousel ">
            @foreach (var item in Model.Blogs)
            {
                if (DateTime.Now<item.CreateDate.AddDays(3) || item.CreateDate<DateTime.Now )
                {
                    <div class="item container-fluid" style="height:400px">
                    <img src="/Img/@item.ImageUrl" style="height:400px">
                    <div class="item-content">
                        <div class="main-content">
                            <div class="meta-category">
                                <a asp-controller="Home" asp-action="PostDetail" asp-route-id="@item.Id"><span>@item.BlogTitle</span></a>  
                            </div>
                            <ul class="post-info">
                                <li><a href="#">Admin</a></li>
                                <li><a href="#">@((int)(DateTime.Now - item.CreateDate).TotalDays) Gün önce yayınlandı.</a></li>
                                <li><a href="#">@item.Comments</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
                }
                
            }
            </div>
    </div>
</div>
<!-- Banner Ends Here -->

<section class="blog-posts">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="all-blog-posts">
                    <div class="row">
                        @foreach (var item in Model.Blogs)
                        {
                            <div class="col-lg-12">
                                <div class="blog-post">
                                    <div class="blog-thumb">
                                        <img src="/Img/@item.ImageUrl" alt="">
                                    </div>
                                    <div class="down-content">
                                        <span>Healthy</span>
                                        <a asp-action="PostDetail" asp-route-id="@item.Id"><h4>@item.BlogTitle</h4></a>
                                        <ul class="post-info">
                                            <li><a href="#">Admin</a></li>
                                            <li><a href="#">@item.CreateDate</a></li>
                                        </ul>
                                        @if (item.BlogDescription.Length>200)
                                        {

                                            @Html.Raw(item.BlogDescription.Substring(0,199))
                                            <a asp-controller="Home" asp-action="PostDetail" asp-route-id="@item.Id">Devamı için tıklayınız</a>
                                            
                                        }

                                        else
                                        {
                                            @Html.Raw(item.BlogDescription)
                                        }

                                        <div class="post-options">
                                            <div class="row">
                                                <div class="col-6">
                                                    <ul class="post-tags">
                                                        <li><i class="fa fa-tags"></i></li>
                                                        <li><a href="#">Best Templates</a>,</li>
                                                        <li><a href="#">TemplateMo</a></li>
                                                    </ul>
                                                </div>
                                                <div class="col-6">
                                                    <ul class="post-share">
                                                        <li><i class="fa fa-share-alt"></i></li>
                                                        <li><a href="#">Facebook</a>,</li>
                                                        <li><a href="#">Twitter</a></li>
                                                    </ul>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                        }
                        
                        <div class="col-lg-12">
                            <div class="main-button">
                                <a asp-action="AllBlog">Tüm Bloglar</a>
                            </div>
                        </div>
                        

                    </div>
                </div>
            </div>
            @Html.Partial("SideBarPartial.cshtml")
        </div>
    </div>
</section>

Straßenkarte/Views/Home/SideBarPartial.cshtml
@model BlogsViewModel

<div class="col-lg-4">
    <div class="sidebar">
        <div class="row">
            <div class="col-lg-12">
                <div class="sidebar-item search">
                    <form asp-action="GetBlog" class="d-flex" method="get">
                        <input type="text" class="searchText" placeholder="Search" autocomplete="on" name="aranankelime">
                        <button type="submit" class="btn btn-outline-success">Arama</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item categories">
                    <div class="sidebar-heading">
                        <h2>Kategoriler</h2>
                    </div>
                    <div class="content">
                        <ul>
                            @foreach (var category in Model.CategoriesSelect)
                            {
                                <li><a asp-controller="home" asp-action="Allblog" asp-route-category="@category.Value">@category.Text</a></li>

                            }
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-12">
                <div class="sidebar-item tags">
                    <div class="sidebar-heading">
                        <h2>Etiketler</h2>
                    </div>
                    <div class="content">
                        <ul>
                            @foreach (var item in Model.Blogs)
                            {
                                if (item.Tag!=null)
                                {
                                    <li><a asp-controller="home" asp-action="Allblog" asp-route-tag="@item.Tag.ToString()">@item.Tag</a></li>
                                    
                                }
                            }

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>